module.exports = [
  {
    name: 'Fixed Bobber Rig',
    waterTemp: ['cold', 'warm'],
    type: ['still'],
    depth: ['shallow'],
  },
  {
    name: 'Ned Rig',
    waterTemp: ['cold', 'warm'],
    type: ['finesse'],
    depth: ['shallow'],
  },
  {
    name: 'Texas Rig',
    waterTemp: ['cold', 'warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow', 'deep'],
  },
  {
    name: 'Dropshot Rig',
    waterTemp: ['cold', 'warm'],
    type: ['finesse'],
    depth: ['deep'],
  },
  {
    name: 'Wacky Rig',
    waterTemp: ['warm'],
    type: ['finesse'],
    depth: ['shallow'],
  },
  {
    name: 'Whopper Plopper',
    waterTemp: ['warm'],
    type: ['reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Popper',
    waterTemp: ['warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Frog',
    waterTemp: ['warm'],
    type: ['finesse'],
    depth: ['shallow'],
  },
  {
    name: 'Shallow-Diving Crankbait',
    waterTemp: ['warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Deep-Diving Crankbait',
    waterTemp: ['warm'],
    type: ['finesse', 'reaction'],
    depth: ['deep'],
  },
  {
    name: 'Lipless Crankbait',
    waterTemp: ['cold', 'warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow', 'deep'],
  },
  {
    name: 'Jig',
    waterTemp: ['cold', 'warm'],
    type: ['finesse', 'reaction', 'still'],
    depth: ['shallow', 'deep'],
  },
  {
    name: 'Spoon',
    waterTemp: ['cold', 'warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Spinnerbait',
    waterTemp: ['warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Inline Spinner',
    waterTemp: ['warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Split Shot Rig',
    waterTemp: ['warm', 'cold'],
    type: ['finesse', 'reaction'],
    depth: ['shallow'],
  },
  {
    name: 'Jerkbait',
    waterTemp: ['cold', 'warm'],
    type: ['finesse', 'reaction'],
    depth: ['shallow', 'deep'],
  },
  {
    name: 'Suspended Jerkbait',
    waterTemp: ['cold'],
    type: ['finesse', 'reaction'],
    depth: ['shallow', 'deep'],
  },
]
