module.exports = {
  dictionaries: [
    'en_US',
    'en-gb',
    'softwareTerms',
    'typescript',
    'node',
    'html',
    'css',
    'filetypes',
    'npm',
    'misc',
  ],
  ignorePaths: ['node_modules', '.next', 'public', 'yarn*', 'package.json'],
  words: [
    'tailwindcss',
    'fortawesome',
    'fontawesome',
    'Dropshot',
    'Plopper',
    'Crankbait',
    'Spinnerbait',
    'Jerkbait',
    'Powerbait',
    'banjokaboom',
    'tacklebox',
    'oilprices',
    'forecastday',
    'maxtemp',
    'feelslike',
    'maxwind',
    'hoisin',
    'swimbaits',
    'canifish',
  ],
}
