import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header'
import Nav from './nav'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tacklebox',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <main className="p-24 pt-16 pb-16 bg-cyan-600 mx-auto">{children}</main>
        <Nav></Nav>
      </body>
    </html>
  )
}
