module.exports = [
  {
    name: 'Grilled Steak',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.5,
    ingredients: [
      'steak',
      'Spicy Montreal Steak Seasoning',
      'rice',
      'bell peppers',
      'sliced mushrooms',
      'onion',
    ],
  },
  {
    name: 'Grilled Chicken',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.75,
    ingredients: ['chicken', 'garlic & herb seasoning', 'rice'],
  },
  {
    name: 'Fish',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 1,
    ingredients: ['fish', 'salmon seasoning', 'basmati rice'],
  },
  {
    name: 'Sausage & Potatoes',
    seasons: ['fall', 'winter'],
    frequency: 0.5,
    ingredients: ['italian sausage', 'potatoes', 'sweet potatoes'],
  },
  {
    name: 'Pulled Pork',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.5,
    ingredients: [
      'pork butt',
      'rolls',
      'brown sugar',
      'onion',
      'cayenne pepper',
      'sugar',
      'paprika',
      'apple cider vinegar',
      'worcestershire sauce',
      'red pepper flakes',
      'salt',
      'black pepper',
      'dried mustard',
    ],
  },
  {
    name: 'Burgers',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.75,
    ingredients: [
      'beef burgers',
      'burger buns',
      'American cheese',
      'mayonnaise',
      'ketchup',
      'mustard',
    ],
  },
  {
    name: 'Pasta',
    seasons: ['spring', 'fall', 'winter'],
    frequency: 0.25,
    ingredients: ['pasta', 'marinara sauce', 'meatballs'],
  },
  {
    name: 'Short Ribs',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 0.5,
    ingredients: [
      'beef short ribs',
      'beef bouillon',
      'dried rosemary',
      'Montreal steak seasoning',
      'salt',
      'pepper',
      'garlic powder',
      'onion powder',
      'potatoes',
    ],
  },
  {
    name: 'Steak Tips',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.5,
    ingredients: ['steak tips', 'teriyaki sauce', 'rice'],
  },
  {
    name: 'Creole Chicken Casserole',
    seasons: ['spring', 'fall', 'winter'],
    frequency: 0.25,
    ingredients: [
      'chicken',
      'chicken broth',
      'rice',
      'creole seasoning',
      'cream of chicken soup',
      'mozzarella cheese',
    ],
  },
  {
    name: 'Tacos',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 0.25,
    ingredients: [
      'ground beef',
      'taco seasoning',
      'tortillas',
      'taco cheese',
      'taco sauce',
      'shredded lettuce',
      'sour cream',
    ],
  },
  {
    name: 'Chicken Stir Fry',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 0.1,
    ingredients: [
      'chicken',
      'rice vinegar',
      'soy sauce',
      'sriracha',
      'hoisin sauce',
      'stir fry noodles',
      'frozen peas and carrots',
      'frozen corn',
      'frozen green beans',
      'white cooking wine',
      'dried cilantro',
      'dried ginger',
      'olive oil',
    ],
  },
  {
    name: 'Ground Pork Stir Fry',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 0.25,
    ingredients: [
      'ground pork',
      'rice vinegar',
      'soy sauce',
      'dried ginger',
      'olive oil',
      'red pepper flakes',
      'minced garlic',
    ],
  },
  {
    name: 'Grilled Portuguese Chicken',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.5,
    ingredients: ['chicken', 'crushed red pepper', 'minced garlic', 'salt'],
  },
  {
    name: 'Shrimp Scampi',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 0.25,
    ingredients: [
      'frozen shrimp',
      'butter',
      'olive oil',
      'onion powder',
      'minced garlic',
      'red pepper flakes',
      'pasta',
      'salt',
      'black pepper',
      'white cooking wine',
      'lemon',
    ],
  },
  {
    name: 'Slow Cooker Creamy Garlic Chicken',
    seasons: ['fall', 'winter'],
    frequency: 0.25,
    ingredients: [
      'chicken',
      'cream cheese',
      'ricotta cheese',
      'chicken bouillon',
      'minced garlic',
      'olive oil',
      'dried rosemary',
      'dried basil',
      'dried thyme',
      'dried oregano',
      'black pepper',
      'pasta',
      'mozzarella cheese',
    ],
  },
  {
    name: 'Crispy Fried Chicken',
    seasons: ['spring', 'fall', 'winter'],
    frequency: 0.1,
    ingredients: [
      'chicken',
      'flour',
      'garlic salt',
      'paprika',
      'black pepper',
      'eggs',
      'salt',
      'poultry seasoning',
    ],
  },
  {
    name: 'Bruschetta Chicken Pasta',
    seasons: ['spring', 'summer', 'fall', 'winter'],
    frequency: 0.5,
    ingredients: [
      'chicken',
      'roma tomatoes',
      'minced garlic',
      'fresh basil',
      'balsamic vinegar',
      'salt',
      'black pepper',
      'pasta',
      'balsamic glaze',
    ],
  },
  {
    name: 'Creamy Parmesan One Pot Chicken and Rice',
    seasons: ['fall', 'winter'],
    frequency: 0.5,
    ingredients: [
      'chicken',
      'butter',
      'onion powder',
      'minced garlic',
      'black pepper',
      'italian seasoning',
      'salt',
      'chicken broth',
      'basmati rice',
      'heavy cream',
      'parmesan cheese',
    ],
  },
  {
    name: 'Rosemary Chicken',
    seasons: ['fall', 'winter'],
    frequency: 0.75,
    ingredients: [
      'whole chicken',
      'olive oil',
      'minced garlic',
      'black pepper',
      'salt',
    ],
  },
  {
    name: 'Jamaican Jerk Pork Ribs',
    seasons: ['fall', 'winter'],
    frequency: 0.5,
    ingredients: ['country style pork ribs', 'jamaican jerk marinade'],
  },
  {
    name: 'Skillet Chicken and Spinach Parmesan',
    seasons: ['spring', 'fall', 'winter'],
    frequency: 0.5,
    ingredients: [
      'chicken',
      'salt',
      'black pepper',
      'panko breadcrumbs',
      'parmesan cheese',
      'olive oil',
      'marinara sauce',
      'baby spinach',
      'mozzarella cheese',
    ],
  },
  {
    name: 'Jamaican Jerk Chicken Tacos',
    seasons: ['spring', 'summer', 'fall'],
    frequency: 0.5,
    ingredients: [
      'chicken',
      'jerk seasoning',
      'shredded lettuce',
      'cilantro',
      'tortillas',
      'mayonnaise',
    ],
  },
  {
    name: 'Crispy Parmesan Baked Chicken',
    seasons: ['fall', 'winter'],
    frequency: 0.5,
    ingredients: [
      'eggs',
      'lemon juice',
      'minced garlic',
      'parsley',
      'salt',
      'black pepper',
      'breadcrumbs',
      'parmesan cheese',
      'chicken',
      'potatoes',
      'butter',
      'green beans',
    ],
  },
  {
    name: 'Orange Chicken',
    seasons: ['spring', 'fall', 'winter'],
    frequency: 0.5,
    ingredients: [
      'chicken',
      'vegetable oil',
      'oranges',
      'brown sugar',
      'cornstarch',
      'soy sauce',
      'hoisin sauce',
      'rice vinegar',
      'sriracha',
    ],
  },
]
